# Generated by Django 2.1.1 on 2018-09-25 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='标题')),
                ('summary', models.CharField(max_length=400, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='微博内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='创建微博的用户')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64)),
                ('blogs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blogs')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o', to='blogs.Comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
    ]
